// <auto-generated />
using System;
using MeroBolee.Utility;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeroBolee.Migrations
{
    [DbContext(typeof(MeroBoleeDbContext))]
    [Migration("20211101102621_email")]
    partial class email
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeroBolee.Model.AdminStatusEntity", b =>
                {
                    b.Property<int>("Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_status");

                    b.HasKey("Status_Id");

                    b.ToTable("lk_admin_status");

                    b.HasData(
                        new
                        {
                            Status_Id = 1,
                            Status = "Active"
                        },
                        new
                        {
                            Status_Id = 2,
                            Status = "Inactive"
                        },
                        new
                        {
                            Status_Id = 3,
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.AuctionStatusEntity", b =>
                {
                    b.Property<int>("Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auction_status");

                    b.HasKey("Status_Id");

                    b.ToTable("lk_auction_status");

                    b.HasData(
                        new
                        {
                            Status_Id = 1,
                            Status = "Created"
                        },
                        new
                        {
                            Status_Id = 2,
                            Status = "Running"
                        },
                        new
                        {
                            Status_Id = 3,
                            Status = "Closed"
                        },
                        new
                        {
                            Status_Id = 4,
                            Status = "Upcoming"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestDocEntity", b =>
                {
                    b.Property<long>("Doc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bidder_request_doc");

                    b.Property<long>("Request_id")
                        .HasColumnType("bigint")
                        .HasColumnName("request_id");

                    b.HasKey("Doc_id");

                    b.HasIndex("Request_id");

                    b.ToTable("mb_bidder_request_doc");
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestEntity", b =>
                {
                    b.Property<long>("Request_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("request_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Admin_Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("admin_status_id");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.Property<DateTime>("Request_Send_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("request_send_date");

                    b.Property<Guid>("Request_code")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_code");

                    b.Property<long>("Tender_Id")
                        .HasColumnType("bigint")
                        .HasColumnName("tender_id");

                    b.Property<long>("User_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Request_Id");

                    b.HasIndex("Admin_Status_Id");

                    b.HasIndex("Tender_Id");

                    b.HasIndex("User_id");

                    b.ToTable("mb_bidder_request");
                });

            modelBuilder.Entity("MeroBolee.Model.BiddingHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("BiddingRequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quotation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TenderId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BiddingRequestId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("TenderId");

                    b.HasIndex("UserId");

                    b.ToTable("mb_bid_history");
                });

            modelBuilder.Entity("MeroBolee.Model.CategoryEntity", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<int>("Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("Category_Id");

                    b.HasIndex("Status_Id");

                    b.ToTable("lk_category");

                    b.HasData(
                        new
                        {
                            Category_Id = 1,
                            Category = "Transportation",
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(1595),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(1627),
                            Status_Id = 1
                        },
                        new
                        {
                            Category_Id = 2,
                            Category = "Construction",
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(1655),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(1658),
                            Status_Id = 1
                        },
                        new
                        {
                            Category_Id = 3,
                            Category = "Tourism",
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(1673),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(1676),
                            Status_Id = 1
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.CityEntity", b =>
                {
                    b.Property<int>("City_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_title");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<int?>("Municipality_Id")
                        .HasColumnType("int")
                        .HasColumnName("municipality_id");

                    b.Property<int?>("Vdc_Id")
                        .HasColumnType("int")
                        .HasColumnName("vdc_id");

                    b.HasKey("City_Id");

                    b.HasIndex("Municipality_Id");

                    b.HasIndex("Vdc_Id");

                    b.ToTable("mb_city");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyDocumentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminStatusEntityStatus_Id")
                        .HasColumnType("int");

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR(300)")
                        .HasColumnName("DocumentPath");

                    b.Property<int>("DocumentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentTypeyId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Remarks");

                    b.Property<long?>("StatusChangedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("UploadedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdminStatusEntityStatus_Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("DocumentStatusId");

                    b.HasIndex("DocumentTypeyId");

                    b.HasIndex("StatusChangedBy");

                    b.HasIndex("UploadedBy");

                    b.ToTable("mb_company_document");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyEntity", b =>
                {
                    b.Property<long>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<int>("MembershipTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("RegisteredAs")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("MembershipTypeId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("mb_company");

                    b.HasData(
                        new
                        {
                            CompanyId = 1L,
                            Address1 = "Address1",
                            Address2 = "Address2",
                            Address3 = "Address3",
                            City = "Kathmandu",
                            CountryId = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(5182),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(5195),
                            MembershipTypeId = 1,
                            Name = "Test Company",
                            ProvinceId = 3,
                            ReferenceCode = "SP112101161120377",
                            RegisteredAs = "Bidder,BidInviter",
                            Zip = "123"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<int>("CompanyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyTypeId");

                    b.ToTable("mb_company_type");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyTypeLookupEntity", b =>
                {
                    b.Property<int>("Company_Type_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_type_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company_type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_type");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.HasKey("Company_Type_Id");

                    b.ToTable("lk_company_type");

                    b.HasData(
                        new
                        {
                            Company_Type_Id = 1,
                            Company_type = "Transportation",
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(6590),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(6598)
                        },
                        new
                        {
                            Company_Type_Id = 2,
                            Company_type = "Construction",
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(6610),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(6613)
                        },
                        new
                        {
                            Company_Type_Id = 3,
                            Company_type = "Tourism",
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(6622),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 21, 697, DateTimeKind.Local).AddTicks(6625)
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.CountryEntity", b =>
                {
                    b.Property<int>("Country_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("country_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abbre");

                    b.Property<string>("Country_Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_code");

                    b.Property<string>("Country_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_name");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.HasKey("Country_Id");

                    b.ToTable("mb_country");

                    b.HasData(
                        new
                        {
                            Country_Id = 1,
                            Abbre = "NP",
                            Country_Code = "NEP",
                            Country_Name = "Nepal",
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 375, DateTimeKind.Local).AddTicks(8334),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 375, DateTimeKind.Local).AddTicks(8339)
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.DistrictEntity", b =>
                {
                    b.Property<int>("District_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("district_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("District_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district_title");

                    b.Property<int?>("Province_Id")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.HasKey("District_Id");

                    b.HasIndex("Province_Id");

                    b.ToTable("mb_district");
                });

            modelBuilder.Entity("MeroBolee.Model.DocumentStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("lk_document_status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Approve"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Reject"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Requires-New"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.DocumentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("mb_document_type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeName = "Citizenship-Front"
                        },
                        new
                        {
                            Id = 2,
                            TypeName = "Citizenship-Back"
                        },
                        new
                        {
                            Id = 3,
                            TypeName = "Tax Clearance"
                        },
                        new
                        {
                            Id = 4,
                            TypeName = "PAN/VAT Registration"
                        },
                        new
                        {
                            Id = 5,
                            TypeName = "Bank Voucher"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.EmailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<long>("TenderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenderId");

                    b.ToTable("mb_email");
                });

            modelBuilder.Entity("MeroBolee.Model.FAQEntity", b =>
                {
                    b.Property<int>("FAQ_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("faq_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.HasKey("FAQ_id");

                    b.ToTable("mb_FAQ");
                });

            modelBuilder.Entity("MeroBolee.Model.FavouriteCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category_id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<long>("User_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Category_id");

                    b.HasIndex("User_id");

                    b.ToTable("mb_favourite");
                });

            modelBuilder.Entity("MeroBolee.Model.LiveBiddingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("BiddingRequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<string>("Quotation")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("TenderId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BiddingRequestId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("TenderId");

                    b.HasIndex("UserId");

                    b.ToTable("mb_live_bid");
                });

            modelBuilder.Entity("MeroBolee.Model.MailAttachmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attachment");

                    b.Property<int?>("MailEntityMail_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MailEntityMail_id");

                    b.ToTable("mb_mail_attachment");
                });

            modelBuilder.Entity("MeroBolee.Model.MailEntity", b =>
                {
                    b.Property<int>("Mail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mail_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bcc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bcc");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<string>("CC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cc");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("FromEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("from_email");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.Property<string>("ToEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to_email");

                    b.HasKey("Mail_id");

                    b.ToTable("mb_mail_data");
                });

            modelBuilder.Entity("MeroBolee.Model.MaterialFeatureEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FeatureName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feature_name");

                    b.Property<string>("FeatureValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feature_value");

                    b.Property<long>("Material_id")
                        .HasColumnType("bigint")
                        .HasColumnName("material_id");

                    b.HasKey("Id");

                    b.HasIndex("Material_id");

                    b.ToTable("mb_material_feature");
                });

            modelBuilder.Entity("MeroBolee.Model.MembershipTypeEntity", b =>
                {
                    b.Property<int>("Membership_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("membership_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<float>("Discount")
                        .HasColumnType("real")
                        .HasColumnName("discount");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("Duration_Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duration_type");

                    b.Property<string>("Membership_Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<float>("Membership_fee")
                        .HasColumnType("real")
                        .HasColumnName("membership_fee");

                    b.Property<int>("Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Membership_Id");

                    b.HasIndex("Status_Id");

                    b.ToTable("mb_membership");

                    b.HasData(
                        new
                        {
                            Membership_Id = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 373, DateTimeKind.Local).AddTicks(7307),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 375, DateTimeKind.Local).AddTicks(4733),
                            Discount = 0f,
                            Duration = 1,
                            Duration_Type = "Year",
                            Membership_Title = "Registration",
                            Membership_fee = 2000f,
                            Status_Id = 1
                        },
                        new
                        {
                            Membership_Id = 2,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 375, DateTimeKind.Local).AddTicks(5448),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 375, DateTimeKind.Local).AddTicks(5454),
                            Discount = 0f,
                            Duration = 1,
                            Duration_Type = "Year",
                            Membership_Title = "Add New Company",
                            Membership_fee = 1500f,
                            Status_Id = 1
                        },
                        new
                        {
                            Membership_Id = 3,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 375, DateTimeKind.Local).AddTicks(5456),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 375, DateTimeKind.Local).AddTicks(5457),
                            Discount = 0f,
                            Duration = 1,
                            Duration_Type = "Year",
                            Membership_Title = "Renew",
                            Membership_fee = 1000f,
                            Status_Id = 1
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.MunicipalityEntity", b =>
                {
                    b.Property<int>("Municipality_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("municipality_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<int?>("District_id")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("Municipality_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("municipality");

                    b.HasKey("Municipality_id");

                    b.HasIndex("District_id");

                    b.ToTable("mb_municipality");
                });

            modelBuilder.Entity("MeroBolee.Model.PaymentStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Payment_status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_status");

                    b.HasKey("Id");

                    b.ToTable("mb_payment_status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Payment_status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Payment_status = "Paid"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.ProvinceEntity", b =>
                {
                    b.Property<int>("Province_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("province_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Country_Id")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_title");

                    b.HasKey("Province_Id");

                    b.HasIndex("Country_Id");

                    b.ToTable("mb_province");

                    b.HasData(
                        new
                        {
                            Province_Id = 1,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(375),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(380),
                            Province = "Province No. 1"
                        },
                        new
                        {
                            Province_Id = 2,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(383),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(385),
                            Province = "Province No. 2"
                        },
                        new
                        {
                            Province_Id = 3,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(386),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(387),
                            Province = "Bagmati Province"
                        },
                        new
                        {
                            Province_Id = 4,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(389),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(390),
                            Province = "Gandaki Province"
                        },
                        new
                        {
                            Province_Id = 5,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(391),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(392),
                            Province = "Lumbini Province"
                        },
                        new
                        {
                            Province_Id = 6,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(394),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(395),
                            Province = "Karnali Province"
                        },
                        new
                        {
                            Province_Id = 7,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(397),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(398),
                            Province = "Sudurpashchim Province"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.PublishStatus", b =>
                {
                    b.Property<int>("Status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Status_id");

                    b.ToTable("lk_common_status");

                    b.HasData(
                        new
                        {
                            Status_id = 1,
                            Status = "Active"
                        },
                        new
                        {
                            Status_id = 2,
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.RequestHelpEntity", b =>
                {
                    b.Property<int>("Request_help_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_help_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("Help_close_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolve_date");

                    b.Property<int>("Help_status_id")
                        .HasColumnType("int")
                        .HasColumnName("help_status_id");

                    b.Property<string>("Problem_title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("problem_title");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.Property<long>("User_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Request_help_id");

                    b.HasIndex("Help_status_id");

                    b.HasIndex("User_id");

                    b.ToTable("mb_request_help");
                });

            modelBuilder.Entity("MeroBolee.Model.RequestHelpStatus", b =>
                {
                    b.Property<int>("Status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Request_status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_status");

                    b.HasKey("Status_id");

                    b.ToTable("lk_request_help_status");

                    b.HasData(
                        new
                        {
                            Status_id = 1,
                            Request_status = "Requested"
                        },
                        new
                        {
                            Status_id = 2,
                            Request_status = "Approved"
                        },
                        new
                        {
                            Status_id = 3,
                            Request_status = "Running"
                        },
                        new
                        {
                            Status_id = 4,
                            Request_status = "Resolved"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.RoleEntity", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("Role_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.HasKey("Role_Id");

                    b.ToTable("mb_role");

                    b.HasData(
                        new
                        {
                            Role_Id = 1,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(8209),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(8215),
                            Role_Name = "Super Admin"
                        },
                        new
                        {
                            Role_Id = 2,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(8218),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(8219),
                            Role_Name = "Bid Inviter"
                        },
                        new
                        {
                            Role_Id = 3,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(8220),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 376, DateTimeKind.Local).AddTicks(8221),
                            Role_Name = "Bidder"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.TenderEntity", b =>
                {
                    b.Property<long>("Tender_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tender_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Admin_Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("admin_status_id");

                    b.Property<int>("Bid_No")
                        .HasColumnType("int")
                        .HasColumnName("bid_no");

                    b.Property<string>("Cancel_remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cancel_remark");

                    b.Property<int>("Category_Id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("Duration_Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duration_type");

                    b.Property<DateTime>("Last_Request_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_request_date");

                    b.Property<DateTime>("Live_End_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("Live_Start_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("Project_Start_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("project_start_date");

                    b.Property<string>("Source_Fund")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_fund");

                    b.Property<string>("Tender_Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tender_code")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Tender_Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("Tender_Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("Tender_Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("tender_status_id");

                    b.Property<string>("Tender_Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tender_title");

                    b.Property<int>("Tender_live_interval")
                        .HasColumnType("int")
                        .HasColumnName("live_interval");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("posted_by");

                    b.HasKey("Tender_Id");

                    b.HasIndex("Admin_Status_Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Tender_Status_Id");

                    b.HasIndex("UserId");

                    b.ToTable("mb_tender");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderMaterialEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("material");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<long>("Tender_Id")
                        .HasColumnType("bigint")
                        .HasColumnName("tender_id");

                    b.HasKey("Id");

                    b.HasIndex("Tender_Id");

                    b.ToTable("mb_tender_material");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderTermsConditionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Tender_Id")
                        .HasColumnType("bigint")
                        .HasColumnName("tender_id");

                    b.Property<string>("Term_Condition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("term_condition");

                    b.HasKey("Id");

                    b.HasIndex("Tender_Id")
                        .IsUnique();

                    b.ToTable("mb_tender_term_condition");
                });

            modelBuilder.Entity("MeroBolee.Model.UserCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("mb_user_company");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CompanyId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CompanyId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CompanyId = 1L,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.UserEmailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<long>("EmailId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.HasIndex("UserId");

                    b.ToTable("mb_user_email");
                });

            modelBuilder.Entity("MeroBolee.Model.UserEntity", b =>
                {
                    b.Property<long>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Activate_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("activate_date");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("designation");

                    b.Property<DateTime?>("Expried_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired_date");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Person_email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int?>("Role_Id")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int?>("Status_id")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<Guid>("User_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_code")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("username");

                    b.HasKey("User_Id");

                    b.HasIndex("Role_Id");

                    b.HasIndex("Status_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.ToTable("mb_user");

                    b.HasData(
                        new
                        {
                            User_Id = 1L,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 381, DateTimeKind.Local).AddTicks(9677),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 381, DateTimeKind.Local).AddTicks(9696),
                            First_Name = "Super",
                            Last_Name = "Admin",
                            Password = "ZDztlPNVNo1CxEclyEDngQ==",
                            Person_email = "super.admin@test.com",
                            Role_Id = 1,
                            Status_id = 2,
                            User_Code = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            User_Id = 2L,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 387, DateTimeKind.Local).AddTicks(8509),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 387, DateTimeKind.Local).AddTicks(8533),
                            First_Name = "Bid",
                            Last_Name = "Inviter",
                            Password = "ZDztlPNVNo1CxEclyEDngQ==",
                            Person_email = "bid.inviter@test.com",
                            Role_Id = 2,
                            Status_id = 2,
                            User_Code = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            User_Id = 3L,
                            Date_created = new DateTime(2021, 11, 1, 16, 11, 20, 387, DateTimeKind.Local).AddTicks(9124),
                            Date_modified = new DateTime(2021, 11, 1, 16, 11, 20, 387, DateTimeKind.Local).AddTicks(9127),
                            First_Name = "Bid",
                            Last_Name = "Bidder",
                            Password = "ZDztlPNVNo1CxEclyEDngQ==",
                            Person_email = "bid.bidder@test.com",
                            Role_Id = 3,
                            Status_id = 2,
                            User_Code = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.UserExperienceDocEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Experienced_doc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("experience_doc");

                    b.Property<long>("User_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("mb_experience_doc");
                });

            modelBuilder.Entity("MeroBolee.Model.UserStatusEntity", b =>
                {
                    b.Property<int>("Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_status");

                    b.HasKey("Status_Id");

                    b.ToTable("lk_user_status");

                    b.HasData(
                        new
                        {
                            Status_Id = 1,
                            Status = "Registered"
                        },
                        new
                        {
                            Status_Id = 2,
                            Status = "Approved"
                        },
                        new
                        {
                            Status_Id = 3,
                            Status = "Suspended"
                        },
                        new
                        {
                            Status_Id = 4,
                            Status = "Terminated"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.VDCEntity", b =>
                {
                    b.Property<int>("Vdc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vdc_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("datetime")
                        .HasColumnName("date_modified");

                    b.Property<int?>("District_Id")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("Vdc_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vdc");

                    b.HasKey("Vdc_Id");

                    b.HasIndex("District_Id");

                    b.ToTable("mb_vdc");
                });

            modelBuilder.Entity("MeroBolee.Model.WatchListEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Tender_Id")
                        .HasColumnType("bigint")
                        .HasColumnName("tender_id");

                    b.Property<long>("User_Id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Tender_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("mb_watchlist");
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestDocEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.BidderRequestEntity", "BidderRequest")
                        .WithMany("BidderRequestDocs")
                        .HasForeignKey("Request_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BidderRequest");
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.AdminStatusEntity", "AdminStatusEntity")
                        .WithMany()
                        .HasForeignKey("Admin_Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany()
                        .HasForeignKey("Tender_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminStatusEntity");

                    b.Navigation("TenderEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.BiddingHistoryEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.BidderRequestEntity", "BidderRequestEntity")
                        .WithMany()
                        .HasForeignKey("BiddingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderMaterialEntity", "TenderMaterialEntity")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BidderRequestEntity");

                    b.Navigation("TenderEntity");

                    b.Navigation("TenderMaterialEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.CategoryEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.PublishStatus", "Status")
                        .WithMany()
                        .HasForeignKey("Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MeroBolee.Model.CityEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.MunicipalityEntity", "Municipality")
                        .WithMany()
                        .HasForeignKey("Municipality_Id");

                    b.HasOne("MeroBolee.Model.VDCEntity", "VDC")
                        .WithMany()
                        .HasForeignKey("Vdc_Id");

                    b.Navigation("Municipality");

                    b.Navigation("VDC");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyDocumentEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.AdminStatusEntity", null)
                        .WithMany("CompanyDocuments")
                        .HasForeignKey("AdminStatusEntityStatus_Id");

                    b.HasOne("MeroBolee.Model.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.DocumentStatusEntity", "DocumentStatus")
                        .WithMany()
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.DocumentTypeEntity", "DocumentType")
                        .WithMany("CompanyDocuments")
                        .HasForeignKey("DocumentTypeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "StatusChangedUserEntity")
                        .WithMany()
                        .HasForeignKey("StatusChangedBy");

                    b.HasOne("MeroBolee.Model.UserEntity", "UploadUserEntity")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DocumentStatus");

                    b.Navigation("DocumentType");

                    b.Navigation("StatusChangedUserEntity");

                    b.Navigation("UploadUserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CountryEntity", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.MembershipTypeEntity", "MembershipType")
                        .WithMany()
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.ProvinceEntity", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("MembershipType");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyTypeEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.CompanyTypeLookupEntity", "CompanyTypeLookup")
                        .WithMany()
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CompanyTypeLookup");
                });

            modelBuilder.Entity("MeroBolee.Model.DistrictEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.ProvinceEntity", "Province")
                        .WithMany()
                        .HasForeignKey("Province_Id");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("MeroBolee.Model.EmailEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderEntity", "Tender")
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Tender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeroBolee.Model.FavouriteCategoryEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeroBolee.Model.LiveBiddingEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.BidderRequestEntity", "BidderRequestEntity")
                        .WithMany("LiveBiddingEntities")
                        .HasForeignKey("BiddingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderMaterialEntity", "TenderMaterialEntity")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BidderRequestEntity");

                    b.Navigation("TenderEntity");

                    b.Navigation("TenderMaterialEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.MailAttachmentEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.MailEntity", null)
                        .WithMany("Attachments")
                        .HasForeignKey("MailEntityMail_id");
                });

            modelBuilder.Entity("MeroBolee.Model.MaterialFeatureEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.TenderMaterialEntity", "TenderMaterialEntity")
                        .WithMany("MaterialFeatures")
                        .HasForeignKey("Material_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderMaterialEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.MembershipTypeEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.PublishStatus", "Status")
                        .WithMany()
                        .HasForeignKey("Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MeroBolee.Model.MunicipalityEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("District_id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("MeroBolee.Model.ProvinceEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CountryEntity", "Country")
                        .WithMany()
                        .HasForeignKey("Country_Id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MeroBolee.Model.RequestHelpEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.RequestHelpStatus", "RequestHelpStatus")
                        .WithMany()
                        .HasForeignKey("Help_status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestHelpStatus");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.AdminStatusEntity", "AdminStatusEntity")
                        .WithMany()
                        .HasForeignKey("Admin_Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.CategoryEntity", "CategoryEntity")
                        .WithMany()
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.AuctionStatusEntity", "AuctionStatusEntity")
                        .WithMany()
                        .HasForeignKey("Tender_Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminStatusEntity");

                    b.Navigation("AuctionStatusEntity");

                    b.Navigation("CategoryEntity");

                    b.Navigation("Company");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderMaterialEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany("TenderMaterialEntities")
                        .HasForeignKey("Tender_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderTermsConditionEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithOne("TenderTermsConditionEntities")
                        .HasForeignKey("MeroBolee.Model.TenderTermsConditionEntity", "Tender_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.UserCompany", b =>
                {
                    b.HasOne("MeroBolee.Model.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeroBolee.Model.UserEmailEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.EmailEntity", "Email")
                        .WithMany("UserEmails")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeroBolee.Model.UserEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("Role_Id");

                    b.HasOne("MeroBolee.Model.UserStatusEntity", "UserStatus")
                        .WithMany()
                        .HasForeignKey("Status_id");

                    b.Navigation("Role");

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("MeroBolee.Model.UserExperienceDocEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeroBolee.Model.VDCEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("District_Id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("MeroBolee.Model.WatchListEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany()
                        .HasForeignKey("Tender_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TenderEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.AdminStatusEntity", b =>
                {
                    b.Navigation("CompanyDocuments");
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestEntity", b =>
                {
                    b.Navigation("BidderRequestDocs");

                    b.Navigation("LiveBiddingEntities");
                });

            modelBuilder.Entity("MeroBolee.Model.DocumentTypeEntity", b =>
                {
                    b.Navigation("CompanyDocuments");
                });

            modelBuilder.Entity("MeroBolee.Model.EmailEntity", b =>
                {
                    b.Navigation("UserEmails");
                });

            modelBuilder.Entity("MeroBolee.Model.MailEntity", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderEntity", b =>
                {
                    b.Navigation("TenderMaterialEntities");

                    b.Navigation("TenderTermsConditionEntities");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderMaterialEntity", b =>
                {
                    b.Navigation("MaterialFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
