// <auto-generated />
using System;
using MeroBolee.Utility;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeroBolee.Migrations
{
    [DbContext(typeof(MeroBoleeDbContext))]
    [Migration("20210802135637_addingFirstTime")]
    partial class addingFirstTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeroBolee.Model.AdminStatusEntity", b =>
                {
                    b.Property<int>("Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_status");

                    b.HasKey("Status_Id");

                    b.ToTable("mb_admin_status");
                });

            modelBuilder.Entity("MeroBolee.Model.AuctionStatusEntity", b =>
                {
                    b.Property<int>("Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auction_status");

                    b.HasKey("Status_Id");

                    b.ToTable("mb_auction_status");
                });

            modelBuilder.Entity("MeroBolee.Model.CategoryEntity", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.Property<int>("Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("Category_Id");

                    b.HasIndex("Status_Id");

                    b.ToTable("mb_category");
                });

            modelBuilder.Entity("MeroBolee.Model.CityEntity", b =>
                {
                    b.Property<int>("City_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_title");

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.Property<int?>("Municipality_Id")
                        .HasColumnType("int")
                        .HasColumnName("municipality_id");

                    b.Property<int?>("Vdc_Id")
                        .HasColumnType("int")
                        .HasColumnName("vdc_id");

                    b.HasKey("City_Id");

                    b.HasIndex("Municipality_Id");

                    b.HasIndex("Vdc_Id");

                    b.ToTable("mb_city");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyTypeEntity", b =>
                {
                    b.Property<int>("Company_Type_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_type_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company_type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_type");

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.HasKey("Company_Type_Id");

                    b.ToTable("mb_company_type");
                });

            modelBuilder.Entity("MeroBolee.Model.CountryEntity", b =>
                {
                    b.Property<int>("Country_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("country_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abbre");

                    b.Property<string>("Country_Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_code");

                    b.Property<string>("Country_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_name");

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.HasKey("Country_Id");

                    b.ToTable("mb_country");
                });

            modelBuilder.Entity("MeroBolee.Model.DistrictEntity", b =>
                {
                    b.Property<int>("District_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("district_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("District_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district_title");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.Property<int?>("Province_Id")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.HasKey("District_Id");

                    b.HasIndex("Province_Id");

                    b.ToTable("mb_district");
                });

            modelBuilder.Entity("MeroBolee.Model.MembershipTypeEntity", b =>
                {
                    b.Property<int>("Membership_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("membership_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<float>("Discount")
                        .HasColumnType("real")
                        .HasColumnName("discount");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("Duration_Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duration_type");

                    b.Property<string>("Membership_Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<float>("Membership_fee")
                        .HasColumnType("real")
                        .HasColumnName("membership_fee");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.Property<int>("Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Membership_Id");

                    b.HasIndex("Status_Id");

                    b.ToTable("mb_membership");
                });

            modelBuilder.Entity("MeroBolee.Model.MunicipalityEntity", b =>
                {
                    b.Property<int>("Municipality_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("municipality_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<int?>("District_id")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.Property<string>("Municipality_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("municipality");

                    b.HasKey("Municipality_id");

                    b.HasIndex("District_id");

                    b.ToTable("mb_municipality");
                });

            modelBuilder.Entity("MeroBolee.Model.ProvinceEntity", b =>
                {
                    b.Property<int>("Province_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("province_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Country_Id")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_title");

                    b.HasKey("Province_Id");

                    b.HasIndex("Country_Id");

                    b.ToTable("mb_province");
                });

            modelBuilder.Entity("MeroBolee.Model.PublishStatus", b =>
                {
                    b.Property<int>("Status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Status_id");

                    b.ToTable("mb_common_status");
                });

            modelBuilder.Entity("MeroBolee.Model.RoleEntity", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.Property<string>("Role_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.HasKey("Role_Id");

                    b.ToTable("mb_role");
                });

            modelBuilder.Entity("MeroBolee.Model.UserEntity", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Activate_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("activate_date");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address2");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address3");

                    b.Property<string>("Back_Citizenship")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("back_citizenship");

                    b.Property<string>("Bank_credit_letter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_credit_letter");

                    b.Property<int>("Category_Id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int>("City_Id")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("Company_Contact1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_contact1");

                    b.Property<string>("Company_Contact2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_contact2");

                    b.Property<string>("Company_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_name");

                    b.Property<string>("Company_Registration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_registration");

                    b.Property<int>("Company_Type_Id")
                        .HasColumnType("int")
                        .HasColumnName("company_type_Id");

                    b.Property<string>("Company_acronym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acronym");

                    b.Property<string>("Company_email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comapny_email");

                    b.Property<int>("Country_Id")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("designation");

                    b.Property<int>("District_Id")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<int>("Employee_no")
                        .HasColumnType("int")
                        .HasColumnName("no_of_employee");

                    b.Property<DateTime?>("Expried_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired_date");

                    b.Property<string>("Fax_No")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fax_no");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("Front_Citizenship")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("front_citizenship");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<int>("Membership_Id")
                        .HasColumnType("int")
                        .HasColumnName("membership_Id");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("middle_name");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.Property<int>("Municipality_Id")
                        .HasColumnType("int")
                        .HasColumnName("municipality_id");

                    b.Property<string>("Pan_Vat_Registration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pan_vat_registration");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Person_contact1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("person_contact1");

                    b.Property<string>("Person_contact2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("person_contact2");

                    b.Property<string>("Person_email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("person_email");

                    b.Property<int>("Province_Id")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<int>("Register_Country")
                        .HasColumnType("int")
                        .HasColumnName("register_country_id");

                    b.Property<string>("Registration_No")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registration_no");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Salutation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("salutation");

                    b.Property<string>("Tax_Clearance")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tax_clearance");

                    b.Property<int?>("UserStatusStatus_Id")
                        .HasColumnType("int");

                    b.Property<Guid>("User_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_code")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("username");

                    b.Property<string>("Vat_Pan_No")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vat_pan_no");

                    b.Property<int>("Vdc_id")
                        .HasColumnType("int")
                        .HasColumnName("vdc_id");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("website");

                    b.HasKey("User_Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("City_Id");

                    b.HasIndex("Company_Type_Id");

                    b.HasIndex("Country_Id");

                    b.HasIndex("District_Id");

                    b.HasIndex("Membership_Id");

                    b.HasIndex("Municipality_Id");

                    b.HasIndex("Province_Id");

                    b.HasIndex("Role_Id");

                    b.HasIndex("UserStatusStatus_Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.HasIndex("Vdc_id");

                    b.ToTable("mb_user");
                });

            modelBuilder.Entity("MeroBolee.Model.UserExperienceDocEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Experienced_doc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("experience_doc");

                    b.Property<int?>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("mb_experience_doc");
                });

            modelBuilder.Entity("MeroBolee.Model.UserStatusEntity", b =>
                {
                    b.Property<int>("Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_status");

                    b.HasKey("Status_Id");

                    b.ToTable("mb_user_status");
                });

            modelBuilder.Entity("MeroBolee.Model.VDCEntity", b =>
                {
                    b.Property<int>("Vdc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vdc_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Created_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<int?>("District_Id")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<TimeSpan>("Modified_time_stamp")
                        .HasColumnType("time")
                        .HasColumnName("modified_timestamp");

                    b.Property<string>("Vdc_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vdc");

                    b.HasKey("Vdc_Id");

                    b.HasIndex("District_Id");

                    b.ToTable("mb_vdc");
                });

            modelBuilder.Entity("MeroBolee.Model.CategoryEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.PublishStatus", "Status")
                        .WithMany()
                        .HasForeignKey("Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MeroBolee.Model.CityEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.MunicipalityEntity", "Municipality")
                        .WithMany()
                        .HasForeignKey("Municipality_Id");

                    b.HasOne("MeroBolee.Model.VDCEntity", "VDC")
                        .WithMany()
                        .HasForeignKey("Vdc_Id");

                    b.Navigation("Municipality");

                    b.Navigation("VDC");
                });

            modelBuilder.Entity("MeroBolee.Model.DistrictEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.ProvinceEntity", "Province")
                        .WithMany()
                        .HasForeignKey("Province_Id");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("MeroBolee.Model.MembershipTypeEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.PublishStatus", "Status")
                        .WithMany()
                        .HasForeignKey("Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MeroBolee.Model.MunicipalityEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("District_id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("MeroBolee.Model.ProvinceEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CountryEntity", "Country")
                        .WithMany()
                        .HasForeignKey("Country_Id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MeroBolee.Model.UserEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.CityEntity", "City")
                        .WithMany()
                        .HasForeignKey("City_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.CompanyTypeEntity", "CompanyType")
                        .WithMany()
                        .HasForeignKey("Company_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.CountryEntity", "Country")
                        .WithMany()
                        .HasForeignKey("Country_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("District_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.MembershipTypeEntity", "MembershipType")
                        .WithMany()
                        .HasForeignKey("Membership_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.MunicipalityEntity", "Municipality")
                        .WithMany()
                        .HasForeignKey("Municipality_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.ProvinceEntity", "Province")
                        .WithMany()
                        .HasForeignKey("Province_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserStatusEntity", "UserStatus")
                        .WithMany()
                        .HasForeignKey("UserStatusStatus_Id");

                    b.HasOne("MeroBolee.Model.VDCEntity", "VDC")
                        .WithMany()
                        .HasForeignKey("Vdc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("CompanyType");

                    b.Navigation("Country");

                    b.Navigation("District");

                    b.Navigation("MembershipType");

                    b.Navigation("Municipality");

                    b.Navigation("Province");

                    b.Navigation("Role");

                    b.Navigation("UserStatus");

                    b.Navigation("VDC");
                });

            modelBuilder.Entity("MeroBolee.Model.UserExperienceDocEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.UserEntity", "User")
                        .WithMany("Experienced_document")
                        .HasForeignKey("User_Id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeroBolee.Model.VDCEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("District_Id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("MeroBolee.Model.UserEntity", b =>
                {
                    b.Navigation("Experienced_document");
                });
#pragma warning restore 612, 618
        }
    }
}
