// <auto-generated />
using System;
using MeroBolee.Utility;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeroBolee.Migrations
{
    [DbContext(typeof(MeroBoleeDbContext))]
    [Migration("20211003112247_company_doc_entity")]
    partial class company_doc_entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeroBolee.Model.AdminStatusEntity", b =>
                {
                    b.Property<int>("Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_status");

                    b.HasKey("Status_Id");

                    b.ToTable("mb_admin_status");

                    b.HasData(
                        new
                        {
                            Status_Id = 1,
                            Status = "Active"
                        },
                        new
                        {
                            Status_Id = 2,
                            Status = "Inactive"
                        },
                        new
                        {
                            Status_Id = 3,
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.AuctionStatusEntity", b =>
                {
                    b.Property<int>("Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auction_status");

                    b.HasKey("Status_Id");

                    b.ToTable("mb_auction_status");

                    b.HasData(
                        new
                        {
                            Status_Id = 1,
                            Status = "Created"
                        },
                        new
                        {
                            Status_Id = 2,
                            Status = "Running"
                        },
                        new
                        {
                            Status_Id = 3,
                            Status = "Closed"
                        },
                        new
                        {
                            Status_Id = 4,
                            Status = "Upcoming"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestDocEntity", b =>
                {
                    b.Property<int>("Doc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bidder_request_doc");

                    b.Property<int>("Request_id")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("Doc_id");

                    b.HasIndex("Request_id");

                    b.ToTable("mb_bidder_request_doc");
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestEntity", b =>
                {
                    b.Property<int>("Request_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Admin_Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("admin_status_id");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.Property<DateTime>("Request_Send_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("request_send_date");

                    b.Property<Guid>("Request_code")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_code");

                    b.Property<int>("Tender_Id")
                        .HasColumnType("int")
                        .HasColumnName("tender_id");

                    b.Property<int>("User_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Request_Id");

                    b.HasIndex("Admin_Status_Id");

                    b.HasIndex("Tender_Id");

                    b.HasIndex("User_id");

                    b.ToTable("mb_bidder_request");
                });

            modelBuilder.Entity("MeroBolee.Model.CallActionEmailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EmailSentOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MailBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("mb_callaction_email");
                });

            modelBuilder.Entity("MeroBolee.Model.CategoryEntity", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<int>("Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("Category_Id");

                    b.HasIndex("Status_Id");

                    b.ToTable("mb_category");

                    b.HasData(
                        new
                        {
                            Category_Id = 1,
                            Category = "Transportation",
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(1700),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(1734),
                            Status_Id = 1
                        },
                        new
                        {
                            Category_Id = 2,
                            Category = "Construction",
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(1778),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(1782),
                            Status_Id = 1
                        },
                        new
                        {
                            Category_Id = 3,
                            Category = "Tourism",
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(1798),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(1801),
                            Status_Id = 1
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.CityEntity", b =>
                {
                    b.Property<int>("City_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_title");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<int?>("Municipality_Id")
                        .HasColumnType("int")
                        .HasColumnName("municipality_id");

                    b.Property<int?>("Vdc_Id")
                        .HasColumnType("int")
                        .HasColumnName("vdc_id");

                    b.HasKey("City_Id");

                    b.HasIndex("Municipality_Id");

                    b.HasIndex("Vdc_Id");

                    b.ToTable("mb_city");
                });

            modelBuilder.Entity("MeroBolee.Model.ClarificationEmailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrespondenceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EmailSentOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MailBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorrespondenceId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("mb_clarification_email");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyDocumentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminStatusEntityStatus_Id")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR(300)")
                        .HasColumnName("DocumentPath");

                    b.Property<int>("DocumentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentTypeyId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Remarks");

                    b.Property<int?>("StatusChangedBy")
                        .HasColumnType("int");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminStatusEntityStatus_Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("DocumentStatusId");

                    b.HasIndex("DocumentTypeyId");

                    b.HasIndex("StatusChangedBy");

                    b.HasIndex("UploadedBy");

                    b.ToTable("mb_company_document");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyEntity", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("mb_company");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Address1 = "Address1",
                            Address2 = "Address2",
                            Address3 = "Address3",
                            City = "Kathmandu",
                            CountryId = 1,
                            Name = "Test Company",
                            ProvinceId = 3,
                            Zip = "123"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyTypeEntity", b =>
                {
                    b.Property<int>("Company_Type_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_type_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company_type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_type");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.HasKey("Company_Type_Id");

                    b.ToTable("mb_company_type");

                    b.HasData(
                        new
                        {
                            Company_Type_Id = 1,
                            Company_type = "Transportation",
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(9222),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(9244)
                        },
                        new
                        {
                            Company_Type_Id = 2,
                            Company_type = "Construction",
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(9259),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(9262)
                        },
                        new
                        {
                            Company_Type_Id = 3,
                            Company_type = "Tourism",
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(9273),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 47, 499, DateTimeKind.Local).AddTicks(9277)
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.CorrespondenceEmailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EmailSentOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MailBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("TenderId");

                    b.ToTable("mb_correspondence_email");
                });

            modelBuilder.Entity("MeroBolee.Model.CountryEntity", b =>
                {
                    b.Property<int>("Country_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("country_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abbre");

                    b.Property<string>("Country_Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_code");

                    b.Property<string>("Country_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_name");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.HasKey("Country_Id");

                    b.ToTable("mb_country");

                    b.HasData(
                        new
                        {
                            Country_Id = 1,
                            Abbre = "NP",
                            Country_Code = "NEP",
                            Country_Name = "Nepal",
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 523, DateTimeKind.Local).AddTicks(4497),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(2659)
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.DistrictEntity", b =>
                {
                    b.Property<int>("District_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("district_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("District_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district_title");

                    b.Property<int?>("Province_Id")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.HasKey("District_Id");

                    b.HasIndex("Province_Id");

                    b.ToTable("mb_district");
                });

            modelBuilder.Entity("MeroBolee.Model.DocumentStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("mb_document_status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Approve"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Reject"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Requires-New"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.DocumentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("mb_document_type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeName = "Citizenship-Front"
                        },
                        new
                        {
                            Id = 2,
                            TypeName = "Citizenship-Back"
                        },
                        new
                        {
                            Id = 3,
                            TypeName = "Tax Clearance"
                        },
                        new
                        {
                            Id = 4,
                            TypeName = "PAN/VAT Registration"
                        },
                        new
                        {
                            Id = 5,
                            TypeName = "Bank Voucher"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.FAQEntity", b =>
                {
                    b.Property<int>("FAQ_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("faq_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.Property<int>("Status_id")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("FAQ_id");

                    b.HasIndex("Status_id");

                    b.ToTable("mb_FAQ");
                });

            modelBuilder.Entity("MeroBolee.Model.FavouriteCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category_id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int>("User_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Category_id");

                    b.HasIndex("User_id");

                    b.ToTable("mb_favourite");
                });

            modelBuilder.Entity("MeroBolee.Model.LiveBiddingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BiddingRequestId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quotation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BiddingRequestId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TenderId");

                    b.ToTable("mb_live_bid");
                });

            modelBuilder.Entity("MeroBolee.Model.MailAttachmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attachment");

                    b.Property<int?>("MailEntityMail_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MailEntityMail_id");

                    b.ToTable("mb_mail_attachment");
                });

            modelBuilder.Entity("MeroBolee.Model.MailEntity", b =>
                {
                    b.Property<int>("Mail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mail_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bcc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bcc");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<string>("CC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cc");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("FromEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("from_email");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.Property<string>("ToEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to_email");

                    b.HasKey("Mail_id");

                    b.ToTable("mb_mail_data");
                });

            modelBuilder.Entity("MeroBolee.Model.MaterialFeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FeatureName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feature_name");

                    b.Property<string>("FeatureValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feature_value");

                    b.Property<int>("Material_id")
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    b.HasKey("Id");

                    b.HasIndex("Material_id");

                    b.ToTable("mb_material_feature");
                });

            modelBuilder.Entity("MeroBolee.Model.MembershipTypeEntity", b =>
                {
                    b.Property<int>("Membership_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("membership_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<float>("Discount")
                        .HasColumnType("real")
                        .HasColumnName("discount");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("Duration_Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duration_type");

                    b.Property<string>("Membership_Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<float>("Membership_fee")
                        .HasColumnType("real")
                        .HasColumnName("membership_fee");

                    b.Property<int>("Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Membership_Id");

                    b.HasIndex("Status_Id");

                    b.ToTable("mb_membership");
                });

            modelBuilder.Entity("MeroBolee.Model.MunicipalityEntity", b =>
                {
                    b.Property<int>("Municipality_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("municipality_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<int?>("District_id")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("Municipality_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("municipality");

                    b.HasKey("Municipality_id");

                    b.HasIndex("District_id");

                    b.ToTable("mb_municipality");
                });

            modelBuilder.Entity("MeroBolee.Model.PaymentStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Payment_status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_status");

                    b.HasKey("Id");

                    b.ToTable("mb_payment_status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Payment_status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Payment_status = "Paid"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.ProvinceEntity", b =>
                {
                    b.Property<int>("Province_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("province_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Country_Id")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_title");

                    b.HasKey("Province_Id");

                    b.HasIndex("Country_Id");

                    b.ToTable("mb_province");

                    b.HasData(
                        new
                        {
                            Province_Id = 1,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4593),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4600),
                            Province = "Province No. 1"
                        },
                        new
                        {
                            Province_Id = 2,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4604),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4605),
                            Province = "Province No. 2"
                        },
                        new
                        {
                            Province_Id = 3,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4606),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4608),
                            Province = "Bagmati Province"
                        },
                        new
                        {
                            Province_Id = 4,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4609),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4610),
                            Province = "Gandaki Province"
                        },
                        new
                        {
                            Province_Id = 5,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4612),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4613),
                            Province = "Lumbini Province"
                        },
                        new
                        {
                            Province_Id = 6,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4614),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4615),
                            Province = "Karnali Province"
                        },
                        new
                        {
                            Province_Id = 7,
                            Country_Id = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4616),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(4617),
                            Province = "Sudurpashchim Province"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.PublishStatus", b =>
                {
                    b.Property<int>("Status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Status_id");

                    b.ToTable("mb_common_status");

                    b.HasData(
                        new
                        {
                            Status_id = 1,
                            Status = "Active"
                        },
                        new
                        {
                            Status_id = 2,
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.RequestHelpEntity", b =>
                {
                    b.Property<int>("Request_help_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_help_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("Help_close_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolve_date");

                    b.Property<int>("Help_status_id")
                        .HasColumnType("int")
                        .HasColumnName("help_status_id");

                    b.Property<string>("Problem_title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("problem_title");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.Property<int>("User_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Request_help_id");

                    b.HasIndex("Help_status_id");

                    b.HasIndex("User_id");

                    b.ToTable("mb_request_help");
                });

            modelBuilder.Entity("MeroBolee.Model.RequestHelpStatus", b =>
                {
                    b.Property<int>("Status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Request_status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_status");

                    b.HasKey("Status_id");

                    b.ToTable("mb_request_help_status");

                    b.HasData(
                        new
                        {
                            Status_id = 1,
                            Request_status = "Requested"
                        },
                        new
                        {
                            Status_id = 2,
                            Request_status = "Approved"
                        },
                        new
                        {
                            Status_id = 3,
                            Request_status = "Running"
                        },
                        new
                        {
                            Status_id = 4,
                            Request_status = "Resolved"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.RoleEntity", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("Role_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.HasKey("Role_Id");

                    b.ToTable("mb_role");

                    b.HasData(
                        new
                        {
                            Role_Id = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(9232),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(9238),
                            Role_Name = "Super Admin"
                        },
                        new
                        {
                            Role_Id = 2,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(9240),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(9241),
                            Role_Name = "Bid Inviter"
                        },
                        new
                        {
                            Role_Id = 3,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(9243),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 524, DateTimeKind.Local).AddTicks(9244),
                            Role_Name = "Bidder"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.TenderEntity", b =>
                {
                    b.Property<int>("Tender_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tender_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Admin_Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("admin_status_id");

                    b.Property<int>("Bid_No")
                        .HasColumnType("int")
                        .HasColumnName("bid_no");

                    b.Property<string>("Cancel_remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cancel_remark");

                    b.Property<int>("Category_Id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("Duration_Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duration_type");

                    b.Property<DateTime>("Last_Request_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_request_date");

                    b.Property<DateTime>("Live_End_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("Live_Start_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<int>("Posted_By")
                        .HasColumnType("int")
                        .HasColumnName("posted_by");

                    b.Property<DateTime>("Project_Start_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("project_start_date");

                    b.Property<string>("Source_Fund")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_fund");

                    b.Property<Guid>("Tender_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tender_code")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Tender_Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("Tender_Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("Tender_Status_Id")
                        .HasColumnType("int")
                        .HasColumnName("tender_status_id");

                    b.Property<string>("Tender_Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tender_title");

                    b.Property<int>("Tender_live_interval")
                        .HasColumnType("int")
                        .HasColumnName("live_interval");

                    b.HasKey("Tender_Id");

                    b.HasIndex("Admin_Status_Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("Posted_By");

                    b.HasIndex("Tender_Status_Id");

                    b.ToTable("mb_tender");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderMaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("material");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("Tender_Id")
                        .HasColumnType("int")
                        .HasColumnName("tender_id");

                    b.HasKey("Id");

                    b.HasIndex("Tender_Id");

                    b.ToTable("mb_tender_material");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderTermsConditionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tender_Id")
                        .HasColumnType("int")
                        .HasColumnName("tender_id");

                    b.Property<string>("Term_Condition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("term_condition");

                    b.HasKey("Id");

                    b.HasIndex("Tender_Id");

                    b.ToTable("mb_tender_term_condition");
                });

            modelBuilder.Entity("MeroBolee.Model.UserEntity", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Activate_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("activate_date");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address2");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address3");

                    b.Property<string>("Back_Citizenship")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("back_citizenship");

                    b.Property<string>("Bank_credit_letter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_credit_letter");

                    b.Property<int?>("Category_Id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int?>("City_Id")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Company_Contact1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_contact1");

                    b.Property<string>("Company_Contact2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_contact2");

                    b.Property<string>("Company_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_name");

                    b.Property<string>("Company_Registration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_registration");

                    b.Property<int?>("Company_Type_Id")
                        .HasColumnType("int")
                        .HasColumnName("company_type_Id");

                    b.Property<string>("Company_acronym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acronym");

                    b.Property<string>("Company_email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comapny_email");

                    b.Property<int?>("Country_Id")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("designation");

                    b.Property<int?>("District_Id")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<int>("Employee_no")
                        .HasColumnType("int")
                        .HasColumnName("no_of_employee");

                    b.Property<DateTime?>("Expried_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired_date");

                    b.Property<string>("Fax_No")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fax_no");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("Front_Citizenship")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("front_citizenship");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<int?>("Membership_Id")
                        .HasColumnType("int")
                        .HasColumnName("membership_Id");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("middle_name");

                    b.Property<int?>("Municipality_Id")
                        .HasColumnType("int")
                        .HasColumnName("municipality_id");

                    b.Property<string>("Pan_Vat_Registration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pan_vat_registration");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Person_contact1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("person_contact1");

                    b.Property<string>("Person_contact2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("person_contact2");

                    b.Property<string>("Person_email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("person_email");

                    b.Property<int?>("Province_Id")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<int>("Register_Country")
                        .HasColumnType("int")
                        .HasColumnName("register_country_id");

                    b.Property<string>("Registration_No")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registration_no");

                    b.Property<int?>("Role_Id")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Salutation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("salutation");

                    b.Property<int?>("Status_id")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<string>("Tax_Clearance")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tax_clearance");

                    b.Property<Guid>("User_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_code")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("username");

                    b.Property<string>("Vat_Pan_No")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vat_pan_no");

                    b.Property<int?>("Vdc_id")
                        .HasColumnType("int")
                        .HasColumnName("vdc_id");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("website");

                    b.HasKey("User_Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("City_Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Company_Type_Id");

                    b.HasIndex("Country_Id");

                    b.HasIndex("District_Id");

                    b.HasIndex("Membership_Id");

                    b.HasIndex("Municipality_Id");

                    b.HasIndex("Province_Id");

                    b.HasIndex("Role_Id");

                    b.HasIndex("Status_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.HasIndex("Vdc_id");

                    b.ToTable("mb_user");

                    b.HasData(
                        new
                        {
                            User_Id = 1,
                            CompanyId = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 525, DateTimeKind.Local).AddTicks(5093),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 525, DateTimeKind.Local).AddTicks(5101),
                            Employee_no = 0,
                            First_Name = "Super",
                            Last_Name = "Admin",
                            Password = "YHCTM7byxNlmg1x9CGp5nA==",
                            Person_email = "super.admin@test.com",
                            Register_Country = 0,
                            Role_Id = 1,
                            Status_id = 2,
                            User_Code = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            User_Id = 2,
                            CompanyId = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 528, DateTimeKind.Local).AddTicks(7142),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 528, DateTimeKind.Local).AddTicks(7160),
                            Employee_no = 0,
                            First_Name = "Bid",
                            Last_Name = "Inviter",
                            Password = "YHCTM7byxNlmg1x9CGp5nA==",
                            Person_email = "bid.inviter@test.com",
                            Register_Country = 0,
                            Role_Id = 2,
                            Status_id = 2,
                            User_Code = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            User_Id = 3,
                            CompanyId = 1,
                            Date_created = new DateTime(2021, 10, 3, 17, 7, 46, 528, DateTimeKind.Local).AddTicks(7494),
                            Date_modified = new DateTime(2021, 10, 3, 17, 7, 46, 528, DateTimeKind.Local).AddTicks(7497),
                            Employee_no = 0,
                            First_Name = "Bid",
                            Last_Name = "Bidder",
                            Password = "YHCTM7byxNlmg1x9CGp5nA==",
                            Person_email = "bid.bidder@test.com",
                            Register_Country = 0,
                            Role_Id = 3,
                            Status_id = 2,
                            User_Code = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.UserExperienceDocEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Experienced_doc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("experience_doc");

                    b.Property<int>("User_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("mb_experience_doc");
                });

            modelBuilder.Entity("MeroBolee.Model.UserStatusEntity", b =>
                {
                    b.Property<int>("Status_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_status");

                    b.HasKey("Status_Id");

                    b.ToTable("mb_user_status");

                    b.HasData(
                        new
                        {
                            Status_Id = 1,
                            Status = "Registered"
                        },
                        new
                        {
                            Status_Id = 2,
                            Status = "Approved"
                        },
                        new
                        {
                            Status_Id = 3,
                            Status = "Suspended"
                        },
                        new
                        {
                            Status_Id = 4,
                            Status = "Terminated"
                        });
                });

            modelBuilder.Entity("MeroBolee.Model.VDCEntity", b =>
                {
                    b.Property<int>("Vdc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vdc_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("Date_modified")
                        .HasColumnType("date")
                        .HasColumnName("date_modified");

                    b.Property<int?>("District_Id")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("Vdc_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vdc");

                    b.HasKey("Vdc_Id");

                    b.HasIndex("District_Id");

                    b.ToTable("mb_vdc");
                });

            modelBuilder.Entity("MeroBolee.Model.WatchListEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tender_Id")
                        .HasColumnType("int")
                        .HasColumnName("tender_id");

                    b.Property<int>("User_Id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Tender_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("mb_watchlist");
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestDocEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.BidderRequestEntity", "BidderRequest")
                        .WithMany("BidderRequestDocs")
                        .HasForeignKey("Request_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BidderRequest");
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.AdminStatusEntity", "AdminStatusEntity")
                        .WithMany()
                        .HasForeignKey("Admin_Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany()
                        .HasForeignKey("Tender_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminStatusEntity");

                    b.Navigation("TenderEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.CallActionEmailEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CallActionEmailEntity", "ParentEmail")
                        .WithMany("Responses")
                        .HasForeignKey("ParentId");

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentEmail");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.CategoryEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.PublishStatus", "Status")
                        .WithMany()
                        .HasForeignKey("Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MeroBolee.Model.CityEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.MunicipalityEntity", "Municipality")
                        .WithMany()
                        .HasForeignKey("Municipality_Id");

                    b.HasOne("MeroBolee.Model.VDCEntity", "VDC")
                        .WithMany()
                        .HasForeignKey("Vdc_Id");

                    b.Navigation("Municipality");

                    b.Navigation("VDC");
                });

            modelBuilder.Entity("MeroBolee.Model.ClarificationEmailEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CorrespondenceEmailEntity", "CorrespondenceEmailEntity")
                        .WithMany()
                        .HasForeignKey("CorrespondenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorrespondenceEmailEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyDocumentEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.AdminStatusEntity", null)
                        .WithMany("CompanyDocuments")
                        .HasForeignKey("AdminStatusEntityStatus_Id");

                    b.HasOne("MeroBolee.Model.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.DocumentStatusEntity", "DocumentStatus")
                        .WithMany()
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.DocumentTypeEntity", "DocumentType")
                        .WithMany("CompanyDocuments")
                        .HasForeignKey("DocumentTypeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "StatusChangedUserEntity")
                        .WithMany()
                        .HasForeignKey("StatusChangedBy");

                    b.HasOne("MeroBolee.Model.UserEntity", "UploadUserEntity")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DocumentStatus");

                    b.Navigation("DocumentType");

                    b.Navigation("StatusChangedUserEntity");

                    b.Navigation("UploadUserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.CompanyEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CountryEntity", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.ProvinceEntity", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("MeroBolee.Model.CorrespondenceEmailEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderEntity", "Tender")
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeroBolee.Model.DistrictEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.ProvinceEntity", "Province")
                        .WithMany()
                        .HasForeignKey("Province_Id");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("MeroBolee.Model.FAQEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.PublishStatus", "PublishStatus")
                        .WithMany()
                        .HasForeignKey("Status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublishStatus");
                });

            modelBuilder.Entity("MeroBolee.Model.FavouriteCategoryEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeroBolee.Model.LiveBiddingEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.BidderRequestEntity", "BidderRequestEntity")
                        .WithMany("LiveBiddingEntities")
                        .HasForeignKey("BiddingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderMaterialEntity", "TenderMaterialEntity")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BidderRequestEntity");

                    b.Navigation("TenderEntity");

                    b.Navigation("TenderMaterialEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.MailAttachmentEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.MailEntity", null)
                        .WithMany("Attachments")
                        .HasForeignKey("MailEntityMail_id");
                });

            modelBuilder.Entity("MeroBolee.Model.MaterialFeatureEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.TenderMaterialEntity", "TenderMaterialEntity")
                        .WithMany("MaterialFeatures")
                        .HasForeignKey("Material_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderMaterialEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.MembershipTypeEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.PublishStatus", "Status")
                        .WithMany()
                        .HasForeignKey("Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MeroBolee.Model.MunicipalityEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("District_id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("MeroBolee.Model.ProvinceEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CountryEntity", "Country")
                        .WithMany()
                        .HasForeignKey("Country_Id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MeroBolee.Model.RequestHelpEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.RequestHelpStatus", "RequestHelpStatus")
                        .WithMany()
                        .HasForeignKey("Help_status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestHelpStatus");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.AdminStatusEntity", "AdminStatusEntity")
                        .WithMany()
                        .HasForeignKey("Admin_Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.CategoryEntity", "CategoryEntity")
                        .WithMany()
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("Posted_By")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.AuctionStatusEntity", "AuctionStatusEntity")
                        .WithMany()
                        .HasForeignKey("Tender_Status_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminStatusEntity");

                    b.Navigation("AuctionStatusEntity");

                    b.Navigation("CategoryEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderMaterialEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany("TenderMaterialEntities")
                        .HasForeignKey("Tender_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderTermsConditionEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany("TenderTermsConditionEntities")
                        .HasForeignKey("Tender_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.UserEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("Category_Id");

                    b.HasOne("MeroBolee.Model.CityEntity", "City")
                        .WithMany()
                        .HasForeignKey("City_Id");

                    b.HasOne("MeroBolee.Model.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.CompanyTypeEntity", "CompanyType")
                        .WithMany()
                        .HasForeignKey("Company_Type_Id");

                    b.HasOne("MeroBolee.Model.CountryEntity", "Country")
                        .WithMany()
                        .HasForeignKey("Country_Id");

                    b.HasOne("MeroBolee.Model.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("District_Id");

                    b.HasOne("MeroBolee.Model.MembershipTypeEntity", "MembershipType")
                        .WithMany()
                        .HasForeignKey("Membership_Id");

                    b.HasOne("MeroBolee.Model.MunicipalityEntity", "Municipality")
                        .WithMany("User_entity")
                        .HasForeignKey("Municipality_Id");

                    b.HasOne("MeroBolee.Model.ProvinceEntity", "Province")
                        .WithMany()
                        .HasForeignKey("Province_Id");

                    b.HasOne("MeroBolee.Model.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("Role_Id");

                    b.HasOne("MeroBolee.Model.UserStatusEntity", "UserStatus")
                        .WithMany()
                        .HasForeignKey("Status_id");

                    b.HasOne("MeroBolee.Model.VDCEntity", "VDC")
                        .WithMany("User_entity")
                        .HasForeignKey("Vdc_id");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("CompanyType");

                    b.Navigation("Country");

                    b.Navigation("District");

                    b.Navigation("MembershipType");

                    b.Navigation("Municipality");

                    b.Navigation("Province");

                    b.Navigation("Role");

                    b.Navigation("UserStatus");

                    b.Navigation("VDC");
                });

            modelBuilder.Entity("MeroBolee.Model.UserExperienceDocEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.UserEntity", "User")
                        .WithMany("Experienced_document")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeroBolee.Model.VDCEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("District_Id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("MeroBolee.Model.WatchListEntity", b =>
                {
                    b.HasOne("MeroBolee.Model.TenderEntity", "TenderEntity")
                        .WithMany()
                        .HasForeignKey("Tender_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeroBolee.Model.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TenderEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("MeroBolee.Model.AdminStatusEntity", b =>
                {
                    b.Navigation("CompanyDocuments");
                });

            modelBuilder.Entity("MeroBolee.Model.BidderRequestEntity", b =>
                {
                    b.Navigation("BidderRequestDocs");

                    b.Navigation("LiveBiddingEntities");
                });

            modelBuilder.Entity("MeroBolee.Model.CallActionEmailEntity", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("MeroBolee.Model.DocumentTypeEntity", b =>
                {
                    b.Navigation("CompanyDocuments");
                });

            modelBuilder.Entity("MeroBolee.Model.MailEntity", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("MeroBolee.Model.MunicipalityEntity", b =>
                {
                    b.Navigation("User_entity");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderEntity", b =>
                {
                    b.Navigation("TenderMaterialEntities");

                    b.Navigation("TenderTermsConditionEntities");
                });

            modelBuilder.Entity("MeroBolee.Model.TenderMaterialEntity", b =>
                {
                    b.Navigation("MaterialFeatures");
                });

            modelBuilder.Entity("MeroBolee.Model.UserEntity", b =>
                {
                    b.Navigation("Experienced_document");
                });

            modelBuilder.Entity("MeroBolee.Model.VDCEntity", b =>
                {
                    b.Navigation("User_entity");
                });
#pragma warning restore 612, 618
        }
    }
}
